/*Class Name  : CalendarEvent
Author        : Venkat Koppolu
Created Date  : 10th Jan 2018
Description   : Wrapper class to hold event information to be displayed on to the calendar*/
public class CalendarEvent {
            public String id;
            public String title {get;set;}
            public String tooltip;
            public String description;
            public String color;
            public String textColor;
            public String tooltipTitle;
            public String tooltipStyleClass;
            public String reason;
     		public String start;
            public String endDateTime;
           
 }